### ISSUE TITLE
Decluttering the repo

### ISSUE THREAD

**Issue by tklebel** [on-merrit/ON-MERRIT#3]
Hi @bikashg !

We will most likely create separate repositories for the different tasks (for example @njahn82 is going to create one for T4.3) so we can have the different analyses in separate repositories. I think it makes a lot of sense to have more than one single large repository, otherwise the git history is very confusing.

It seems to me that all work that has been done until now in this repo lives under T3.1. Is that correct? If yes, we could safely remove everything else and rename the repo to something informative. At the moment I'm not certain, how we should structure repos within WP3 though - so we should probably discuss this.
I already went ahead and deleted WPs 1 & 2 in this repo, since they are definitely not going to do some data analysis.

**Comment by bikashg** [comment]
Hi @tklebel 

If the other work packages want to use different repositories, that is fine with us. With regards to WP3, we would like to keep the structure organized per tasks, as it is at the moment. Definitely open for discussion regarding other changes, if any.

**Comment by tklebel** [comment]
Ok! I'll leave WP3 as it is, and remove the rest.

**Comment by tklebel** [comment]
done as of 31c04f326f14adb818a65bec869d780296a7ef27
