### ISSUE TITLE
Add CC0 license

### ISSUE THREAD

**Issue by tklebel** [on-merrit/ON-MERRIT#4]
The repo currently doesn't have a license which is not good. According to our DMP, we usually would use a CC0. Is that ok with you @bikashg, or are there strong arguments against it? To your knowledge, does the repo contain any other licensed conted (except for the cookiecutter template)?

**Comment by bikashg** [comment]
Its just the cookiecutter for now, which is a MIT license.

**Comment by tklebel** [comment]
Ok. I'll then include MIT as pertaining to the template, and CC0 as pertaining to our code.
